# Generated by Django 2.2.9 on 2020-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_auto_20200405_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(
                upload_to='news_pictures/', verbose_name=u"Add image (optional)",
                blank=True, null=True
            ),
            preserve_default=False,
        ),
    ]
