# Generated by Django 2.0.3 on 2018-06-03 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180513_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
