# Generated by Django 2.2.9 on 2020-04-19 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_list',
            field=models.ManyToManyField(blank=True, related_name='contacters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_list',
            field=models.ManyToManyField(blank=True, related_name='my_pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
