# Generated by Django 2.2.9 on 2020-05-14 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
