# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20170701_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('E', 'Edited Article'), ('S', 'Also Commented'), ('I', 'Logged In'), ('O', 'Logged Out'), ('U', 'Up Voted Question'), ('V', 'Up Voted Answer')], max_length=1),
        ),
    ]
