# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180319_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='question',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('S', 'Also Commented'), ('I', 'Logged In'), ('O', 'Logged Out')], max_length=1),
        ),
    ]
