# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
