# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20171017_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
