# Generated by Django 2.2.9 on 2020-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('L', 'liked'), ('C', 'commented'), ('F', 'favorited'), ('A', 'answered'), ('W', 'accepted'), ('E', 'edited'), ('K', 'also commented'), ('I', 'logged in'), ('O', 'logged out'), ('V', 'voted on'), ('S', 'shared'), ('U', 'created an account'), ('X', 'followed you'), ('Y', 'sent you a friend request'), ('Z', 'accepted your friend request')], max_length=1),
        ),
    ]
