# Generated by Django 2.0.3 on 2018-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_object_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_object_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted'), ('E', 'Edited'), ('K', 'Also commented'), ('I', 'Logged In'), ('O', 'Logged Out'), ('V', 'Voted on'), ('S', 'Shared')], max_length=1),
        ),
    ]
