# Generated by Django 2.0.3 on 2018-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180329_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_object_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
