# Generated by Django 2.2.9 on 2021-11-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200511_1308'),
        ('notifications', '0003_auto_20200512_0041'),
    ]

    operations = [
    ]
