# Generated by Django 2.0.3 on 2018-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20180414_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_object_object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
