# Generated by Django 2.0.3 on 2018-06-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_object_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_on', to='contenttypes.ContentType'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_content_type',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'content_type', 'object_id', 'value')},
        ),
        migrations.AlterIndexTogether(
            name='vote',
            index_together={('content_type', 'object_id')},
        ),
    ]
