# Generated by Django 2.0.3 on 2018-07-04 00:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
