# Generated by Django 2.0.3 on 2018-06-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20180609_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='liked',
        ),
    ]
