# Generated by Django 2.0.3 on 2018-06-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_remove_answer_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='liked',
        ),
    ]
