# Generated by Django 2.0.3 on 2018-06-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_remove_question_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
