# Generated by Django 2.0.3 on 2018-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_question_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
