# Generated by Django 2.0.3 on 2018-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0002_auto_20180508_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
